const wordList = [
    { word: "kot", hint: "zwierze domowe" },
    { word: "samochod", hint: "srodek transportu" },
    { word: "drzwi", hint: "czesc budynku" },
    { word: "telefon", hint: "urzadzenie komunikacyjne" },
    { word: "ksiazka", hint: "zbior tekstow" },
    { word: "okno", hint: "czesc budynku" },
    { word: "banan", hint: "owoc" },
    { word: "pilka", hint: "przedmiot sportowy" },
    { word: "komputer", hint: "urzadzenie elektroniczne" },
    { word: "szkola", hint: "miejsce nauki" },
    { word: "kuchnia", hint: "pomieszczenie domowe" },
    { word: "chleb", hint: "produkt spozywczy" },
    { word: "dziecko", hint: "maly czlowiek" },
    { word: "krzeslo", hint: "meble" },
    { word: "szczotka", hint: "narzedzie do czyszczenia" },
    { word: "nozyce", hint: "narzedzie do ciecia" },
    { word: "kawa", hint: "napoj" },
    { word: "aparat", hint: "urzadzenie fotograficzne" },
    { word: "zegar", hint: "urzadzenie czasomierza" },
    { word: "papier", hint: "material pisarski" },
    { word: "kotlet", hint: "potrawa miesna" },
    { word: "kabel", hint: "przewod elektryczny" },
    { word: "klucz", hint: "narzedzie do otwierania" },
    { word: "kominek", hint: "miejsce ogrzewania" },
    { word: "rozek", hint: "slodka przekaska" },
    { word: "balon", hint: "przedmiot nadmuchiwany" },
    { word: "krakow", hint: "smierdzi" },
    { word: "oczko", hint: "czesc igly" },
    { word: "krew", hint: "cialo plynne" },
    { word: "sojka", hint: "ptak" },
    { word: "milosc", hint: "paczki" },
    { word: "trawa", hint: "roslina" },
    { word: "deska", hint: "plaska powierzchnia" },
    { word: "swieczka", hint: "dekoracyjne zrodlo swiatla" },
    { word: "kanapa", hint: "meble" },
    { word: "mleko", hint: "napoj" },
    { word: "dzwiek", hint: "czuly zmysl" },
    { word: "pasta", hint: "sposob przechowywania" },
    { word: "koszulka", hint: "czesc garderoby" },
    { word: "szczur", hint: "gryzon" },
    { word: "lustro", hint: "przedmiot odbijajacy obraz" },
    { word: "krokodyl", hint: "duzy gad" },
    { word: "krok", hint: "czesc drogi" },
    { word: "palka", hint: "pret" },
    { word: "ser", hint: "produkt mleczarski" },
    { word: "paczek", hint: "slodka przekaska" },
    { word: "trampolina", hint: "urzadzenie do skakania" },
    { word: "dlugopis", hint: "narzedzie do pisania" },
    { word: "plecak", hint: "pojemnik na rzeczy" },
    { word: "kanalizacja", hint: "system odprowadzania wody" },
    { word: "kubeczek", hint: "pojemnik na plyny" },
    { word: "portfel", hint: "przechowywane pieniadze" },
    { word: "komar", hint: "owad" },
    { word: "kula", hint: "kolisty przedmiot" },
    { word: "komorka", hint: "urzadzenie komunikacyjne" },
    { word: "mis", hint: "pluszowa zabawka" },
    { word: "kielbasa", hint: "produkt miesny" },
    { word: "okulary", hint: "przedmiot do widzenia" },
    { word: "kotla", hint: "naczynie do gotowania" },
    { word: "sol", hint: "substancja do przyprawiania" },
    { word: "szafka", hint: "meble do przechowywania" },
    { word: "lalka", hint: "zabawka" },
    { word: "klawiatura", hint: "czesc komputera" },
    { word: "klawisz", hint: "czesc instrumentu" },
    { word: "saxofon", hint: "instrument muzyczny" },
    { word: "foka", hint: "zwierze morskie" },
    { word: "ryz", hint: "ziarno" },
    { word: "makaron", hint: "produkt spozywczy" },
    { word: "kafelki", hint: "czesc wykonczenia podlogi" },
    { word: "koniec", hint: "zakonczenie" },
    { word: "olowek", hint: "narzedzie do pisania" },
    { word: "kapusta", hint: "warzywo" },
    { word: "szpinak", hint: "warzywo" },
    { word: "biedronka", hint: "owad" },
    { word: "filizofia", hint: "dziedzina nauki" },
    { word: "piec", hint: "liczba naturalna" },
    { word: "krewetka", hint: "skorupiak" },
    { word: "jajko", hint: "produkt spozywczy" },
    { word: "koc", hint: "koldra" },
    { word: "miod", hint: "produkt pszczeli" },
    { word: "pianka", hint: "piana" },
    { word: "szczotka", hint: "narzedzie do czyszczenia" },
    { word: "kolo", hint: "figura geometryczna" },
    { word: "kabanos", hint: "wedliny" },
    { word: "maslo", hint: "produkt mleczny" },
    { word: "wolowina", hint: "mieso" },
    { word: "jablko", hint: "owoc" },
    { word: "zegarek", hint: "urzadzenie do mierzenia czasu" },
    { word: "bawcia", hint: "starsza osoba" },
    { word: "stol", hint: "meble" },
    { word: "nosidlo", hint: "urzadzenie do noszenia rzeczy" },
    { word: "kaleka", hint: "osoba niepelnosprawna" },
    { word: "klawiatura", hint: "urzadzenie do pisania" },
    { word: "ciasto", hint: "slodka przekaska" },
    { word: "pies", hint: "zwierze domowe" },
    { word: "szyba", hint: "czesc okna" },
    { word: "debata", hint: "dyskusja" },
    { word: "lodz", hint: "pojazd wodny" },
    { word: "gra", hint: "rozrywka" },
    { word: "malarz", hint: "osoba malujaca" },
    { word: "zabawka", hint: "przedmiot do zabawy" },
    { word: "pilot", hint: "urzadzenie do sterowania" },
    { word: "nauczyciel", hint: "xD" },
    { word: "kwiat", hint: "roslina" },
    { word: "woz", hint: "srodek transportu" },
    { word: "wasy", hint: "czesc twarzy" },
    { word: "grill", hint: "urzadzenie do grillowania" },
    { word: "ocean", hint: "wielka woda" },
    { word: "wioslo", hint: "narzedzie do plywania" },
    { word: "drewno", hint: "material budowlany" },
    { word: "port", hint: "miejsce statkow" },
    { word: "klon", hint: "drzewo" },
    { word: "zima", hint: "jedna z por roku" },
    { word: "szklo", hint: "material" },
    { word: "cytryna", hint: "owoc" },
    { word: "gruby", hint: "okreslenie budowy ciala" },
    { word: "serce", hint: "czesc ciala" },
    { word: "krok", hint: "jeden krok" },
    { word: "wiatr", hint: "zjawisko atmosferyczne" },
    { word: "pies", hint: "zwierze domowe" },
    { word: "brazylia", hint: "kraj" },
    { word: "gora", hint: "element krajobrazu" },
    { word: "pepeseza", hint: "przedmiot dekoracyjny" },
    { word: "zab", hint: "czesc ciala" },
    { word: "pajak", hint: "gad" },
    { word: "kot", hint: "zwierze domowe" },
    { word: "piatek", hint: "jeden z dni tygodnia" },
    { word: "krokodyl", hint: "gad" },
    { word: "jakob", hint: "imie meskie" },
    { word: "licencja", hint: "dokument" },
    { word: "wozek", hint: "urzadzenie do przemieszczania" },
    { word: "diament", hint: "kamien szlachetny" },
    { word: "muzyka", hint: "dzwieki" },
    { word: "bazaar", hint: "rodzaj targu" },
    { word: "balet", hint: "forma taneczna" },
    { word: "dywan", hint: "element wyposazenia wnetrza" },
    { word: "roza", hint: "kwiat" },
    { word: "szachy", hint: "gra logiczna" },
    { word: "urodziny", hint: "swieto" },
    { word: "pokojowka", hint: "osoba wykonujaca prace domowa" },
    { word: "malarstwo", hint: "sztuka" },
    { word: "czapka", hint: "czesc garderoby" },
    { word: "bawarka", hint: "rodzaj alkoholu" },
    { word: "gasior", hint: "ptak" },
    { word: "kasza", hint: "produkt spozywczy" },
    { word: "krowa", hint: "zwierze hodowlane" },
    { word: "buk", hint: "drzewo" },
    { word: "smiech", hint: "dzwiek" },
    { word: "zebra", hint: "krowa w paski" },
    { word: "trampolina", hint: "urzadzenie do skakania" },
    { word: "taras", hint: "element budynku" },
    { word: "dynia", hint: "warzywo" },
    { word: "pierogi", hint: "potrawa" },
    { word: "kometa", hint: "zjawisko kosmiczne" },
    { word: "karton", hint: "material" },
    { word: "dieta", hint: "odzywianie" },
    { word: "lis", hint: "zwierze" },
    { word: "kosz", hint: "pojemnik" },
    { word: "sos", hint: "przyprawa" },
    { word: "cykl", hint: "okres czasu" },
    { word: "cien", hint: "brak swiatla" },
    { word: "tornado", hint: "zjawisko atmosferyczne" },
    { word: "lodka", hint: "pojazd wodny" },
    { word: "ekologia", hint: "dziedzina nauki" },
    { word: "rosek", hint: "rodzaj mgly" },
    { word: "jogurt", hint: "produkt spozywczy" },
    { word: "kolej", hint: "srodek transportu" },
    { word: "oranzada", hint: "napoj" },
    { word: "zywnosc", hint: "produkt spozywczy" },
    { word: "scierka", hint: "material czyszczacy" },
    { word: "karania", hint: "reakcja na zle zachowanie" },
    { word: "ekran", hint: "element urzadzenia" },
    { word: "kilka", hint: "liczba" },
    { word: "osiol", hint: "zwierze" },
    { word: "rysunek", hint: "sztuka" },
    { word: "galeria", hint: "miejsce wystawowe" },
    { word: "krewetka", hint: "skorupiak" },
    { word: "perla", hint: "kamien szlachetny" },
    { word: "laka", hint: "fragment natury" },
    { word: "grzesznik", hint: "osoba popelniajaca grzech" },
    { word: "peron", hint: "miejsce na stacji" },
    { word: "wiosenka", hint: "czas roku" },
    { word: "okrag", hint: "figura geometryczna" },
    { word: "zlodziej", hint: "osoba kradnaca" },
    { word: "ratunek", hint: "pomoc" },
    { word: "rozaneczka", hint: "kwiat" },
    { word: "koszmar", hint: "zly sen" },
    { word: "kucharka", hint: "osoba przygotowujaca jedzenie" },
    { word: "glupota", hint: "brak rozumu" },
    { word: "toksyczny", hint: "szkodliwy dla zdrowia" },
    { word: "karafka", hint: "naczynie do picia" },
    { word: "wycieczka", hint: "podroz rekreacyjna" },
    { word: "szczescie", hint: "stan emocjonalny" },
    { word: "kielkowanie", hint: "proces wzrostu roslin" },
    { word: "lawenda", hint: "roslina ozdobna" },
    { word: "kobieta", hint: "plec" },
    { word: "lad", hint: "porzadek" },
    { word: "osemka", hint: "overrated"},
    { word: "kasztan", hint: "owoc" },
    { word: "pianka", hint: "rodzaj piany" },
    { word: "brak", hint: "nieobecnosc" },
    { word: "widok", hint: "cos co mozna zobaczyc" },
    { word: "czeresnia", hint: "owoc" },
    { word: "wzmacniacz", hint: "urzadzenie elektroniczne" },
    { word: "szampon", hint: "produkt do mycia wlosow" },
    { word: "piasek", hint: "material sypki" },
    { word: "rog", hint: "czesc ciala" },
    { word: "morze", hint: "duza masa wody" },
    { word: "poziom", hint: "wysokosc wzgledem czegos" },
    { word: "papieros", hint: "palenie" },
    { word: "koziol", hint: "zwierze" },
    { word: "luksus", hint: "drogi sposob zycia" },
    { word: "drozdze", hint: "produkt spozywczy" },
    { word: "zabieg", hint: "procedura medyczna" },
    { word: "waski", hint: "przeciwny do szeroki" },
    { word: "panna", hint: "stan cywilny" },
    { word: "nadgarstek", hint: "czesc ciala" },
    { word: "rownoleglosc", hint: "geometria" },
    { word: "karbon", hint: "pierwiastek chemiczny" },
    { word: "wiertlo", hint: "narzedzie do wiercenia" },
    { word: "dach", hint: "czesc budynku" },
    { word: "granica", hint: "granica panstwowa" },
    { word: "pasozyt", hint: "organizm zyjacy kosztem innego organizmu" },
    { word: "wegilowiec", hint: "rodzaj organizmu" },
    { word: "zwrot", hint: "zmiana kierunku" },
    { word: "niepokojacy", hint: "wzbudzajacy niepokoj" },
    { word: "snieg", hint: "opad atmosferyczny" },
    { word: "wieza", hint: "element architektoniczny" },
    { word: "kolejka", hint: "transport publiczny" },
    { word: "ocet", hint: "przyprawa" },
    { word: "plaza", hint: "miejsce wypoczynku" },
    { word: "drzewo", hint: "element przyrody" },
    { word: "sawa", hint: "jezioro" },
    { word: "wanilia", hint: "przyprawa" },
    { word: "cement", hint: "material budowlany" },
    { word: "grunt", hint: "powierzchnia ziemi" },
    { word: "plyta", hint: "element konstrukcyjny" },
    { word: "grozba", hint: "zagrozenie" },
    { word: "kapiel", hint: "procedura higieniczna" },
    { word: "przystanek", hint: "miejsce zatrzymania pojazdu" },
    { word: "kraksa", hint: "wypadek" },
    { word: "hormon", hint: "substancja chemiczna" },
    { word: "pojazd", hint: "srodek transportu" },
    { word: "pierze", hint: "czesc odziezy" },
    { word: "traktor", hint: "rodzaj pojazdu" },
    { word: "kobieta", hint: "plec" },
    { word: "jesien", hint: "jedna z por roku" },
    { word: "podloga", hint: "element budynku" },
    { word: "rana", hint: "czesc dnia" },
    { word: "silnik", hint: "urzadzenie mechaniczne" },
    { word: "orzeszki", hint: "owoc" },
    { word: "urlop", hint: "okres wolny od pracy" },
    { word: "dym", hint: "gaz" },
    { word: "szlifowanie", hint: "proces obrobki" },
    { word: "piekarnia", hint: "miejsce produkujace pieczywo" },
    { word: "spiew", hint: "dzwiek" },
    { word: "szyja", hint: "czesc ciala" },
    { word: "schody", hint: "element budynku" },
    { word: "zlamanie", hint: "uszkodzenie" },
    { word: "smutny", hint: "stan emocjonalny" },
    { word: "gruba", hint: "okreslenie budowy ciala" },
    { word: "przedszkole", hint: "miejsce nauki dla dzieci" },
    { word: "dywagacja", hint: "myslenie" },
    { word: "rozbior", hint: "proces niszczenia" },
    { word: "siostra", hint: "relacja rodzinna" },
    { word: "stary", hint: "przeciwny do mlody" },
    { word: "osiagac", hint: "osiaganie celu" },
    { word: "nastrojony", hint: "stan emocjonalny" },
    { word: "klodka", hint: "element zabezpieczajacy" },
    { word: "glab", hint: "wewnetrzna czesc czegos" },
    { word: "poduszka", hint: "element wyposazenia" },
    { word: "guma", hint: "material" },
    { word: "trawnik", hint: "element ogrodu" },
    { word: "maksymalny", hint: "najwiekszy mozliwy" },
    { word: "wiosenne", hint: "jedna z por roku" },
    { word: "okularnik", hint: "rodzaj okularow" },
    { word: "bank", hint: "miejsce przechowywania pieniedzy"},
]